java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=A -output=tests/1_a_alg_1.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=A -output=tests/1_a_dfs_1.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=C -output=tests/1_a_alg_2.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=C -output=tests/1_a_dfs_2.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=B.C -output=tests/1_a_alg_3.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=B.C -output=tests/1_a_dfs_3.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=A.B -output=tests/1_a_alg_4.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=A.B -output=tests/1_a_dfs_4.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=A+ -output=tests/1_a_alg_5.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=A+ -output=tests/1_a_dfs_5.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=C* -output=tests/1_a_alg_6.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=C* -output=tests/1_a_dfs_6.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=A+.B* -output=tests/1_a_alg_7.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=A+.B* -output=tests/1_a_dfs_7.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=(B.C*)+ -output=tests/1_a_alg_8.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=(B.C*)+ -output=tests/1_a_dfs_8.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=B*.C* -output=tests/1_a_alg_9.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=B*.C* -output=tests/1_a_dfs_9.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=A*.B*.C* -output=tests/1_a_alg_10.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=A*.B*.C* -output=tests/1_a_dfs_10.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=a -rpq=(A*.B*.C*)+ -output=tests/1_a_alg_11.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=a -rpq=(A*.B*.C*)+ -output=tests/1_a_dfs_11.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=A -output=tests/2_sp_alg_1.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=A -output=tests/2_sp_dfs_1.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=C -output=tests/2_sp_alg_2.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=C -output=tests/2_sp_dfs_2.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=B.C -output=tests/2_sp_alg_3.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=B.C -output=tests/2_sp_dfs_3.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=A.B -output=tests/2_sp_alg_4.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=A.B -output=tests/2_sp_dfs_4.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=A+ -output=tests/2_sp_alg_5.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=A+ -output=tests/2_sp_dfs_5.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=C* -output=tests/2_sp_alg_6.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=C* -output=tests/2_sp_dfs_6.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=A+.B* -output=tests/2_sp_alg_7.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=A+.B* -output=tests/2_sp_dfs_7.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=(B.C*)+ -output=tests/2_sp_alg_8.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=(B.C*)+ -output=tests/2_sp_dfs_8.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=B*.C* -output=tests/2_sp_alg_9.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=B*.C* -output=tests/2_sp_dfs_9.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=A*.B*.C* -output=tests/2_sp_alg_10.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=A*.B*.C* -output=tests/2_sp_dfs_10.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=sp -rpq=(A*.B*.C*)+ -output=tests/2_sp_alg_11.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=sp -rpq=(A*.B*.C*)+ -output=tests/2_sp_dfs_11.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=A -output=tests/3_t_alg_1.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=A -output=tests/3_t_dfs_1.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=C -output=tests/3_t_alg_2.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=C -output=tests/3_t_dfs_2.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=B.C -output=tests/3_t_alg_3.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=B.C -output=tests/3_t_dfs_3.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=A.B -output=tests/3_t_alg_4.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=A.B -output=tests/3_t_dfs_4.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=A+ -output=tests/3_t_alg_5.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=A+ -output=tests/3_t_dfs_5.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=C* -output=tests/3_t_alg_6.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=C* -output=tests/3_t_dfs_6.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=A+.B* -output=tests/3_t_alg_7.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=A+.B* -output=tests/3_t_dfs_7.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=(B.C*)+ -output=tests/3_t_alg_8.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=(B.C*)+ -output=tests/3_t_dfs_8.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=B*.C* -output=tests/3_t_alg_9.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=B*.C* -output=tests/3_t_dfs_9.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=A*.B*.C* -output=tests/3_t_alg_10.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=A*.B*.C* -output=tests/3_t_dfs_10.txt
java -jar PathDatabase.jar -algorithm=alg -database=dbfull.txt -semantic=t -rpq=(A*.B*.C*)+ -output=tests/3_t_alg_11.txt
java -jar PathDatabase.jar -algorithm=dfs -database=dbfull.txt -semantic=t -rpq=(A*.B*.C*)+ -output=tests/3_t_dfs_11.txtjava -jar PathDatabase.jar 